
package mesaayudatec;

import dao.LoginDAO;
import mesaayudatec.newpackage.model.MySqlConexion;
import javax.swing.*;
import java.sql.*;
import mesaayudatec.Item;

public class Registro extends javax.swing.JFrame {

    private final int idUsuarioLogueado;
    private final TablaUsuario parent; // referencia a la ventana padre

    // Constructor principal
    public Registro(int idUsuarioLogueado, TablaUsuario parent) {
        this.idUsuarioLogueado = idUsuarioLogueado;
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
        cargarCombos();

        // Listener para manejar cierre con la X
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                volverATablaUsuario();
            }
        });
    }

    // Atajos compatibles
    public Registro(int idUsuarioLogueado) { this(idUsuarioLogueado, null); }
    public Registro() { this(1, null); }

    // --------- CARGAR COMBOS ----------
    private void cargarCombos() {
        ComboHelper.cargarEstados(tb_estados);
        ComboHelper.cargarDepartamentos(tb_departamento);
        ComboHelper.cargarPrioridades(tb_prioridades);
    }

    // --------- GRABAR TICKET ----------
    private void grabarTicket() {
        String titulo = jT_Titulo.getText().trim();
        String descripcion = jT_Descripcion.getText().trim();

        if (titulo.isEmpty() || descripcion.isEmpty()
                || tb_estados.getSelectedItem() == null
                || tb_departamento.getSelectedItem() == null
                || tb_prioridades.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.",
                    "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idEstado    = ComboHelper.getIdSeleccionado(tb_estados);
        int idDepto     = ComboHelper.getIdSeleccionado(tb_departamento);
        int idPrioridad = ComboHelper.getIdSeleccionado(tb_prioridades);

        String folio = "F" + System.currentTimeMillis();

        String sql = """
                INSERT INTO tb_ticket
                (folio, registrado, id_departamento, id_usuario, id_status, id_prioridad, descripcion, titulo)
                VALUES (?, NOW(), ?, ?, ?, ?, ?, ?)
                """;

        try (Connection con = new MySqlConexion().getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, folio);
            ps.setInt(2, idDepto);
            ps.setInt(3, idUsuarioLogueado);
            ps.setInt(4, idEstado);
            ps.setInt(5, idPrioridad);
            ps.setString(6, descripcion);
            ps.setString(7, titulo);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "✅ Incidencia registrada con folio: " + folio);
            jT_Titulo.setText("");
            jT_Descripcion.setText("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage(),
                    "BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    // --------- VOLVER ----------
    private void volverATablaUsuario() {
        if (parent != null) {
            parent.refrescar(); // recargar datos
            parent.setVisible(true);
        } else {
            new Login().setVisible(true); // respaldo
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jT_Titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Descripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        tb_estados = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tb_departamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tb_prioridades = new javax.swing.JComboBox<>();
        jB_Grabar = new javax.swing.JButton();
        jB_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Título");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripción");

        jT_Descripcion.setColumns(20);
        jT_Descripcion.setRows(5);
        jScrollPane1.setViewportView(jT_Descripcion);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Estado");

        tb_estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tb_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_estadosActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Departamento");

        tb_departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tb_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_departamentoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Prioridad");

        tb_prioridades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tb_prioridades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_prioridadesActionPerformed(evt);
            }
        });

        jB_Grabar.setText("Grabar");
        jB_Grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GrabarActionPerformed(evt);
            }
        });

        jB_Volver.setText("Volver");
        jB_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tb_prioridades, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tb_estados, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jT_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_Grabar)
                        .addGap(175, 175, 175)))
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_Volver)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tb_estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tb_prioridades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jB_Grabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jB_Volver)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_estadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_estadosActionPerformed

    private void tb_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_departamentoActionPerformed

    private void tb_prioridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_prioridadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_prioridadesActionPerformed

    private void jB_GrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GrabarActionPerformed

    }//GEN-LAST:event_jB_GrabarActionPerformed

    private void jB_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VolverActionPerformed
  volverATablaUsuario();
        dispose();
    }//GEN-LAST:event_jB_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Grabar;
    private javax.swing.JButton jB_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_Descripcion;
    private javax.swing.JTextField jT_Titulo;
    private javax.swing.JComboBox<String> tb_departamento;
    private javax.swing.JComboBox<String> tb_estados;
    private javax.swing.JComboBox<String> tb_prioridades;
    // End of variables declaration//GEN-END:variables
}
